# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: example-ui-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     # kubernetes.io/ingress.allow-http: "false"
# spec:
#   # tls:
#   #   - secretName: example-ui-ingress 
#   rules:
#     - host: example-ui.default
#       http:
#        paths:
#        - path: /
#          pathType: Prefix
#          backend:
#           service:
#             name: example-ui
#             port:
#               number: 9292
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "example-ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Chart.Name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "example-ui.fullname" . }}
            port:
              number: {{ .Values.service.externalPort }}
          # serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
          # servicePort: 9292
