# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: example-ui
#   labels:
#     app: example-app
#     component: example-ui
# spec:
#   type: NodePort
#   ports:
#   - port: 9292
#     protocol: TCP
#     targetPort: 9292
#   selector:
#     app: example-app
#     component: example-ui
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-{{ .Chart.Name }}
#   labels:
#     app: example-app
#     component: example-ui
#     release: {{ .Release.Name }}
# spec:
#   type: NodePort
#   ports:
#   - port: {{ .Values.service.externalPort }}
#     protocol: TCP
#     targetPort: 9292
#   selector:
#     app: example-app
#     component: example-ui
#     release: {{ .Release.Name }}    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: example-app
    component: example-ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: example-app
    component: example-ui
    release: {{ .Release.Name }}
