---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "example-post.fullname" . }}
  labels:
    app: example-app
    component: example-post
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: example-app
    component: example-post
    release: {{ .Release.Name }}
