image: alpine:latest
variables:
  CI_REGISTRY: "index.docker.io"
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY/$CI_PROJECT_PATH
  CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG
  CI_CONTAINER_NAME: ci_job_bexample-uild_${CI_JOB_ID}
  TILLER_NAMESPACE: "kube-system"
  KUBECONFIG: /root/config

stages:
  - test
  - staging
  - production

test:
  stage: test
  script:
    - exit 0
  only:
    - triggers
    - branches

staging:
  stage: staging
  script:
  # - install_dependencies
  - echo ${kube_config} | base64 -d > ${KUBECONFIG}
  - echo ${ca_pem} | base64 -d > /root/ca.pem
  - apk add -U openssl curl tar gzip bash ca-certificates git
  - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
  - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
  - apk add glibc-2.23-r3.apk
  - rm glibc-2.23-r3.apk
  - curl https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz | tar zx
  - mv linux-amd64/helm /usr/bin/
  - helm version --client
  - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x /usr/bin/kubectl
  - kubectl version --client
  # - ensure_namespace
  - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
  # - install_tiller
  - echo "Checking Tiller..."
  - helm init --client-only --skip-refresh
  - helm repo rm stable
  - helm repo add stable https://charts.helm.sh/stable
  - kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
  - >
    if ! helm version --debug; then
      echo "Failed to init Tiller."
      return 1
    fi
  - echo ""
  # - deploy
  - echo $KUBE_NAMESPACE
  - helm dep bexample-uild example-app
  - helm upgrade --install
    --wait
    --set example-ui.ingress.host="$host"
    --set example-ui.image.tag="$(curl https://gitlab.difica.com/$CI_PROJECT_NAMESPACE/example-ui/raw/master/VERSION)"
    --set example-post.image.tag="$(curl https://gitlab.difica.com/$CI_PROJECT_NAMESPACE/example-post/raw/master/VERSION)"
    --set example-comment.image.tag="$(curl https://gitlab.difica.com/$CI_PROJECT_NAMESPACE/example-comment/raw/master/VERSION)"
    --namespace="$KUBE_NAMESPACE"
    --version="$CI_PIPELINE_ID-$CI_JOB_ID"
    "$name"
    example-app
  variables:
    KUBE_NAMESPACE: staging
    host: staging.$CI_GITLAB_DOMAIN
    track: "${1-stable}"
    name: "$CI_ENVIRONMENT_SLUG"
  environment:
    name: staging
    url: http://staging.$CI_GITLAB_DOMAIN
  only:
    refs:
      - master
    # kubernetes: active

production:
  stage: production
  script:
    # - install_dependencies
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - echo ${ca_pem} | base64 -d > /root/ca.pem
    - apk add -U openssl curl tar gzip bash ca-certificates git
    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
    - apk add glibc-2.23-r3.apk
    - rm glibc-2.23-r3.apk
    - curl https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz | tar zx
    - mv linux-amd64/helm /usr/bin/
    - helm version --client
    - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x /usr/bin/kubectl
    - kubectl version --client

    # - ensure_namespace
    - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"


    # - install_tiller
    - echo "Checking Tiller..."
    - helm init --client-only --skip-refresh
    - helm repo rm stable
    - helm repo add stable https://charts.helm.sh/stable
    - kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
    - >
      if ! helm version --debug; then
        echo "Failed to init Tiller."
        return 1
      fi
    - echo ""
    # - deploy
    - echo $KUBE_NAMESPACE
    - helm dep bexample-uild example-app
    - helm upgrade --install
      --wait
      --set example-ui.ingress.host="$host"
      --set example-ui.image.tag="$(curl https://gitlab.difica.com/$CI_PROJECT_NAMESPACE/example-ui/raw/master/VERSION)"
      --set example-post.image.tag="$(curl https://gitlab.difica.com/$CI_PROJECT_NAMESPACE/example-post/raw/master/VERSION)"
      --set example-comment.image.tag="$(curl https://gitlab.difica.com/$CI_PROJECT_NAMESPACE/example-comment/raw/master/VERSION)"
      --namespace="$KUBE_NAMESPACE"
      --version="$CI_PIPELINE_ID-$CI_JOB_ID"
      "$name" \
      example-app
  variables:
    KUBE_NAMESPACE: production
    host: production.$CI_GITLAB_DOMAIN
    track: "${1-stable}"
    name: "$CI_ENVIRONMENT_SLUG"
  environment:
    name: production
    url: http://production.$CI_GITLAB_DOMAIN
  # when: manual
  only:
    refs:
      - master
    # kubernetes: active
