---
apiVersion: v1
kind: Service
metadata:
  name: example-comment-db
  labels:
    app: example-app
    component: mongo
    example-comment-db: "true"
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: example-app
    component: mongo
    example-comment-db: "true"
