---
apiVersion: v1
kind: Service
metadata:
  name: example-comment
  labels:
    app: example-app
    component: example-comment
spec:
  ports:
  - port: 9292
    protocol: TCP
    targetPort: 9292
  selector:
    app: example-app
    component: example-comment
