---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-post
  labels:
    app: example-app
    component: example-post
    example-post-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
      component: example-post
  template:
    metadata:
      name: example-post
      labels:
        app: example-app
        component: example-post
        example-post-db: "true"
    spec:
      containers:
      - image: mzabolotnov/example-post
        name: example-post
        env:
        - name: POST_DATABASE_HOST
          value: example-post-db
        