---
apiVersion: v1
kind: Service
metadata:
  name: example-post
  labels:
    app: example-app
    component: example-post
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: example-app
    component: example-post
