---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: example-ui-ingress 
  rules:
    - host: mikhza.twilightparadox.com
      http:
       paths:
       - path: /
         pathType: Prefix
         backend:
          service:
            name: example-ui
            port:
              number: 9292

