---
apiVersion: v1
kind: Service
metadata:
  name: example-ui
  labels:
    app: example-app
    component: example-ui
spec:
  type: NodePort
  ports:
  - port: 9292
    protocol: TCP
    targetPort: 9292
  selector:
    app: example-app
    component: example-ui
