---
global:
  scrape_interval: '10s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'example-ui'
    static_configs:
      - targets:
        - 'example-ui:9292'

  - job_name: 'example-comment'
    static_configs:
      - targets:
        - 'example-comment:9292'

  - job_name: 'example-post'
    static_configs:
      - targets:
        - 'example-post:5000'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'mongex'
    static_configs:
      - targets:
        - 'mongodb-exporter:9216'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - example-post
        - example-comment
        - example-ui
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboxexporter:9115
  
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'

  - job_name: 'docker'
    static_configs:
      - targets:
        - 'localhost:9323'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
