apiVersion: v1
kind: Service
metadata:
  name: {{ template "example-postgresql.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: example-postgres
      port: 5432
      targetPort: example-postgres
  selector:
    name: {{ template "example-postgresql.fullname" . }}
