{{- if .Values.example-postgresDedicatedStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "example-postgresql.fullname" . }}-storage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.example-postgresStorageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.example-postgresStorageClass | quote }}
  {{- else if (eq .Values.provider "gke") }}
    volume.beta.kubernetes.io/storage-class: {{ template "fullname" . }}-fast
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.example-postgresAccessMode | quote }}
  resources:
    requests:
      storage: {{ default "30Gi" .Values.example-postgresStorageSize }}
{{- end }}
