apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "example-postgresql.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        name: {{ template "example-postgresql.fullname" . }}
    spec:
      containers:
      - name: example-postgresql
        image: {{ .Values.example-postgresImage }}
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-config
              key: example-postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-secrets
              key: example-postgres_password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-config
              key: example-postgres_db
        - name: DB_EXTENSION
          value: pg_trgm
        - name: PGDATA
          value: /var/lib/example-postgresql/data/pgdata
        ports:
        - name: example-postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/example-postgresql/data
          name: data
          subPath: example-postgres
        - mountPath: /docker-entrypoint-initdb.d
          name: initdb
          readOnly: true
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - example-postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - example-postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ if .Values.example-postgresDedicatedStorage }} {{ template "example-postgresql.fullname" . }}-storage {{ else }} {{ template "fullname" . }}-storage {{ end }}
      - name: initdb
        configMap:
          name: {{ template "example-postgresql.fullname" . }}-initdb
