apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "example-comment.fullname" . }}
  labels:
    app: example-app
    component: example-comment
    release: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
      component: example-comment
      release: {{ .Release.Name }}
  template:
    metadata:
      name: example-comment
      labels:
        app: example-app
        component: example-comment
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: example-comment
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: example-comment
              protocol: TCP
          env:
            - name: COMMENT_DATABASE_HOST
              value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
